version: '3'

services:
  pyt:
    build:
      context: .
      dockerfile: Dockerfile
    image: maytham/pysele
    networks:
      - potato
    command: tail -F anything

  db:
    build:
      context: .
      dockerfile: Dockerfile01
    image: maytham/postgres
    environment:
      - POSTGRES_DB=test
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    port:
      - 5432:5432
    networks:
      - potato
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
volumes:
  postgres-data:
networks:
  potato:
